### ISSUE TITLE
Generate report with github pages

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#146]
In order to automatically deploy the latest report results the following would need to happen:

1. CI is passing, and JSON output files are autoamtically generateted on every merge to main.
2. JSON output files are injected into index.html / respec sections
3. GitHub Pages hosting is set to "gh-pages branch"
4. GitHub Pages deploy is handled via CI

**Comment by shigeya** [comment]
@OR13 With discussion with @msporny

A few things changed while I'm working on the report generation. Since we have 3000+ test results, and the report generation is slow, we don't commit the test result JSON object anymore, also statically generate the report.

1. index.html is removed, the report is currently generated at `packages/did-core-test-suite/report/index.html`
2. We're not injecting JSON to index.html anymore. Report generator reads JSON and generates the index.html from the `report-template.html` template file. 
3. So, what we need is to place the generated index.html file on gh-pages branch.

**Comment by msporny** [comment]
This is done, I think.

@iherman, can you please switch this repository over to serve Github pages from the gh-pages branch?

**Comment by iherman** [comment]
Done, @msporny

**Comment by msporny** [comment]
> Done, @msporny

Confirmed, we are now auto-generating the latest test report and publishing to gh-pages: https://w3c.github.io/did-test-suite/

woo! Thanks to everyone in this issue that made it happen.
