### ISSUE TITLE
Need tests for JSON Production and Consumption

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#26]
[6.2.1 JSON Production \
](https://w3c.github.io/did-core/#production)The [DID document](https://w3c.github.io/did-core/#dfn-did-documents) and any DID document data structures expressed by the [data model](https://w3c.github.io/did-core/#data-model) _MUST_ be serialized to the JSON [representation](https://w3c.github.io/did-core/#dfn-representations) according to the following [production](https://w3c.github.io/did-core/#dfn-production) rules:

<table>
  <tr>
   <td><strong>Data Type</strong>
   </td>
   <td><strong>JSON Representation Type</strong>
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#maps">map</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-4">JSON Object</a>, where each entry is serialized as a member of the JSON Object with the entry key as a <a href="https://tools.ietf.org/html/rfc8259#section-7">JSON String</a> member name and the entry value according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#list">list</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-5">JSON Array</a>, where each element of the list is serialized, in order, as a value of the array according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-5">JSON Array</a>, where each element of the set is added, in order, as a value of the array according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://w3c.github.io/did-core/#dfn-datetime">datetime</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-7">JSON String</a> serialized as an <a href="https://www.w3.org/TR/xmlschema11-2/#dateTime">XML Datetime</a> normalized to UTC 00:00:00 and without sub-second decimal precision. For example: <code>2020-12-20T19:17:47Z</code>.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#string">string</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-7">JSON String</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://w3c.github.io/did-core/#dfn-integer">integer</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-6">JSON Number</a> without a decimal or fractional component.
   </td>
  </tr>
  <tr>
   <td><a href="https://w3c.github.io/did-core/#dfn-double">double</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-6">JSON Number</a> with a decimal and fractional component.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#boolean">boolean</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-3">JSON Boolean</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#null">null</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8259#section-3">JSON null literal</a>.
   </td>
  </tr>
</table>

All entries of a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) _MUST_ be included in the root [JSON Object](https://tools.ietf.org/html/rfc8259#section-4). 

When serializing a [DID document](https://w3c.github.io/did-core/#dfn-did-documents), a [conforming producer](https://w3c.github.io/did-core/#dfn-conforming-producer) _MUST_ specify a media type of `application/did+json` to downstream applications such as described in [§ 7.1.2 DID Resolution Metadata](https://w3c.github.io/did-core/#did-resolution-metadata).

[6.2.2 JSON Consumption \
](https://w3c.github.io/did-core/#consumption)The [DID document](https://w3c.github.io/did-core/#dfn-did-documents) and any DID document data structures expressed by a JSON [representation](https://w3c.github.io/did-core/#dfn-representations) _MUST_ be deserialized into the [data model](https://w3c.github.io/did-core/#data-model) according to the following [consumption](https://w3c.github.io/did-core/#dfn-consumption) rules:

<table>
  <tr>
   <td><strong>JSON Representation Type</strong>
   </td>
   <td><strong>Data Type</strong>
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-4">JSON Object</a>
   </td>
   <td>An <a href="https://infra.spec.whatwg.org/#maps">map</a>, where each member of the JSON Object is added as an entry to the map. Each entry key is set as the JSON Object member name. Each entry value is set by converting the JSON Object member value according to the JSON representation type as defined in this table. Since order is not specified by JSON Objects, no insertion order is guaranteed.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-5">JSON Array</a> where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value is a <a href="https://infra.spec.whatwg.org/#list">list</a> or unknown
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#list">list</a>, where each value of the JSON Array is added to the list in order, converted based on the JSON representation type of the array value, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-5">JSON Array</a> where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value is an <a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>
   </td>
   <td>An <a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>, where each value of the JSON Array is added to the ordered set in order, converted based on the JSON representation type of the array value, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-7">JSON String</a> where <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value is a <a href="https://w3c.github.io/did-core/#dfn-datetime">datetime</a>
   </td>
   <td>A <a href="https://w3c.github.io/did-core/#dfn-datetime">datetime</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-7">JSON String</a>, where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value type is <a href="https://infra.spec.whatwg.org/#string">string</a> or unknown
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#string">string</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-6">JSON Number</a> without a decimal or fractional component
   </td>
   <td>An <a href="https://w3c.github.io/did-core/#dfn-integer">integer</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-6">JSON Number</a> with a decimal and fractional component, or when entry value is a <a href="https://w3c.github.io/did-core/#dfn-double">double</a> regardless of inclusion of fractional component
   </td>
   <td>A <a href="https://w3c.github.io/did-core/#dfn-double">double</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-3">JSON Boolean</a>
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#boolean">boolean</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8259#section-3">JSON null literal</a>
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#null">null</a> value.
   </td>
  </tr>
</table>

If media type information is available to a [conforming consumer](https://w3c.github.io/did-core/#dfn-conforming-consumer) and the media type value is `application/did+json`, then the data structure being consumed is a [DID document](https://w3c.github.io/did-core/#dfn-did-documents), and the root element _MUST_ be a [JSON Object](https://tools.ietf.org/html/rfc8259#section-4) where all members of the object are entries of the [DID document](https://w3c.github.io/did-core/#dfn-did-documents). 

A [conforming consumer](https://w3c.github.io/did-core/#dfn-conforming-consumer) for a JSON [representation](https://w3c.github.io/did-core/#dfn-representations) that is consuming a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) with a root element that is not a [JSON Object](https://tools.ietf.org/html/rfc8259#section-4) _MUST_ report an error.

**Comment by OR13** [comment]
@csuwildcat any chance Microsoft / you can help test the representation you fought so hard for us to include :) ?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-8) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.8. Need tests for CBOR/JSON Production and Consumption 

_See github issue [did-test-suite#28](https://github.com/w3c/did-test-suite/issues/28), [did-test-suite#26](https://github.com/w3c/did-test-suite/issues/26)._




**Markus Sabadello:** those are about sections that don't have tests  
… 28 is about cbor  
… 26 is about json  
… there are test for jsonld production and consumption  
… and for generic sections about production and consumption that are not representation specific  
… it looks like there are no tests yet for cbor and json production and consumption  
… the cbor one is assigned to Orie and json is assigned to Daniel  

**Daniel Burnett:** we were hoping for someone like Jonathan to contribute on the cbor  

**Jonathan Holt:** doing my best to get back in the swing with DID contributions  

**Daniel Burnett:** daniel can you contribute on the json? the json format in particular was one of the biggest requests from Microsoft on day one of the working group  
… so we really want to make sure it's complete  

**Daniel Buchner:** the way we've gone about it I don't know... it's worked perfectly fine working jsonld as json and saying you don't have to resolve contexts  
… I can work on any tests that take that approach  
… that's what we're doing in our implementation  
… make sense?  
… are there bugs or issues out there that want it to be different than that?  

**Markus Sabadello:** i know some people want to treat jsonld and json as equivalent and to include `@context` in both and this has to do with long discussions we had  
… my personal opinion is this is not what the did core spec describes right now  
… it does not envision that json and jsonld are byte to byte equivalent  
… if that's what WG members want to do we should change the did core spec  
… right now on the test suite we need to take the normative statements  
… the open issues on the test suite they list the normative statements that need to be tested  
… so we need to work based on that  

**Justin Richer:** +1 to what markus was saying  
… one of the things that got brought up a necessary test condition is that a did doc that is described to be in plain json should be allowed to have the `@context` field and have it be a completely invalid value, and that should pass  
… that should get parsed, the `@context` dumped into the bucket  
… with whatever value it is  
… no checking if it's an array or string or anything  

> *Daniel Buchner:* Yes Justin, yeeeessss

> *Daniel Buchner:* Love everything you are saying right now

**Justin Richer:** so if you have the `@context` value with boolean false an d a plain json encoding by the way the did core spec is defined today that is allowable  
… because the re-serialization on the producer side needs to be able to place the appropriate context value and not just pass through blindly whatever it was handed  
… I will say I'm not personally familiar with the structure and function of the test suite code to suggest how to contribute this piece and don't have the bandwidth, I apologise for that  
… but that is the type of corner case we need to have tests cases for  
… if you're doing lazy validation that's not proving you're compliant  

**Daniel Buchner:** the interesting thing.. it doesn't say anything about must exclude properties... isn't lazy validation accurate?  
… if you had context with a bool and the spec doesn't say it has to be right isn't the way i'd write the test to not deal with that property?  
… lazy validation is the valid way to do it?  

**Justin Richer:** you need to go one step further because the spec says what to say with unknown properties  
… in this case `@context` would be an unknown property  
… you need to make sure things will accept things with an invalid `@context`  
… that's important  
… not enough to just say if i give you something an call it plain json but it's really jsonld that you'll be happy with that, that's not enough  
… we need to test these kinds of things  
… if you do that by ignoring it using a precise definition of ignore that's in the spec, that's fine  
… that's not lazy validation  
… that's explicitly handling unknown properties in a particular way  

**Daniel Buchner:** instead of completely avoiding it or not putting any lines of code that deal with unknown properties, it'll iterate all the properties and have some sort of if that says if you're not in the set.. log it.. do something.. recognise it exists.. if it is in the set do what you're supposed to do?  

**Justin Richer:** to be specific what it does is processes the serliazed property based on the type value of the serialized property and puts it into the properties map  
… there will be an `@context` with boolean value of false inside the ADM  

> *Daniel Buchner:* ok, this makes sense

> *Daniel Buchner:* thank you justin

**Justin Richer:** when it comes time to do a production from that ADM if you want to do it into jsonld your jsonld producer needs to be able to make sense of that bad `@context` value  
… and either throw an error there or replace it with a good `@context` value on thew ay out which is more likely  
… there are specific rules of how to handle these  
… from a code standpoint it does look like the else at the end of your validators  

**Daniel Buchner:** that's a good answer, thank you  

**Daniel Burnett:** issue 26 about json... Orie had asked in feb whether you might be able to contribute in writing some tests  
… largely this is in here because Microsoft fought hard for it  
… we want to make sure everyone else is not doing all of the test work  

**Daniel Buchner:** I'll try to do something about it  

**Daniel Burnett:** I think that's it for the test issues  

</details>

**Comment by msporny** [comment]
Reminder that complete tests, including review, auditing, and at least one implementation, are due for this item by the end of this month.

**Comment by msporny** [comment]
All JSON Production and Consumption tests have been implemented. Closing.
