### ISSUE TITLE
Need tests for CBOR Production and Consumption

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#28]
6.4.1 CBOR Production

All [DID document](https://w3c.github.io/did-core/#dfn-did-documents) data structures expressed by the [data model](https://w3c.github.io/did-core/#data-model) _MUST_ be serialized to the CBOR [representation](https://w3c.github.io/did-core/#dfn-representations) according to the following [production](https://w3c.github.io/did-core/#dfn-production) rules:

<table>
  <tr>
   <td><strong>Data Type</strong>
   </td>
   <td><strong>CBOR Representation Type</strong>
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#maps">map</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR map</a> (major type 5), where each entry is represented as a member of the CBOR map. The entry key is expressed as a <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3) as the key, and the entry value according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#list">list</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> (major type 4), where each element of the list is added, in order, as a value of the array according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> (major type 4), where each element of the list is added, in order, as a value of the array according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://w3c.github.io/did-core/#dfn-datetime">datetime</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3) formatted as an <a href="https://www.w3.org/TR/xmlschema11-2/#dateTime">XML Datetime</a> normalized to UTC 00:00 and without sub-second decimal precision. For example: <code>2020-12-20T19:17:47Z</code>.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#string">string</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3).
   </td>
  </tr>
  <tr>
   <td><a href="https://w3c.github.io/did-core/#dfn-integer">integer</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR integer</a> (major type 0 or 1), choosing the shortest byte representation.
   </td>
  </tr>
  <tr>
   <td><a href="https://w3c.github.io/did-core/#dfn-double">double</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR floating-point number</a> (major type 7). All floating point values <em>MUST</em> be encoded as 64-bits (additional type value 27), even for integral values.
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#boolean">boolean</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.3">CBOR simple value</a> (major type 7, subtype 24) with a simple value of 21 (true) or 20 (false).
   </td>
  </tr>
  <tr>
   <td><a href="https://infra.spec.whatwg.org/#null">null</a>
   </td>
   <td>A <a href="https://tools.ietf.org/html/rfc8949#section-3.3">CBOR simple value</a> (major type 7, subtype 24) with a simple value of 22 (null).
   </td>
  </tr>
</table>

[6.4.1 CBOR Production](https://w3c.github.io/did-core/#production-1)

All [DID document](https://sites.local/did-core/#dfn-did-documents) data structures expressed by the [data model](https://sites.local/did-core/#data-model) _MUST_ be serialized to the CBOR [representation](https://sites.local/did-core/#dfn-representations) according to the following [production](https://sites.local/did-core/#dfn-production) rules:

<table>
  <tr>
   <td><strong>Data Type</strong>
   </td>
   <td><strong>CBOR Representation Type</strong>
   </td>
  </tr>
  <tr>
   <td>
<a href="https://infra.spec.whatwg.org/#maps">map</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR map</a> (major type 5), where each entry is represented as a member of the CBOR map. The entry key is expressed as a <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3) as the key, and the entry value according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td>
<a href="https://infra.spec.whatwg.org/#list">list</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> (major type 4), where each element of the list is added, in order, as a value of the array according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td>
<a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> (major type 4), where each element of the list is added, in order, as a value of the array according to its type, as defined in this table.
   </td>
  </tr>
  <tr>
   <td>
<a href="https://sites.local/did-core/#dfn-datetime">datetime</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3) formatted as an <a href="https://www.w3.org/TR/xmlschema11-2/#dateTime">XML Datetime</a> normalized to UTC 00:00 and without sub-second decimal precision. For example: <code>2020-12-20T19:17:47Z</code>.
   </td>
  </tr>
  <tr>
   <td>
<a href="https://infra.spec.whatwg.org/#string">string</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3).
   </td>
  </tr>
  <tr>
   <td>
<a href="https://sites.local/did-core/#dfn-integer">integer</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR integer</a> (major type 0 or 1), choosing the shortest byte representation.
   </td>
  </tr>
  <tr>
   <td>
<a href="https://sites.local/did-core/#dfn-double">double</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR floating-point number</a> (major type 7). All floating point values <em>MUST</em> be encoded as 64-bits (additional type value 27), even for integral values.
   </td>
  </tr>
  <tr>
   <td>
<a href="https://infra.spec.whatwg.org/#boolean">boolean</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.3">CBOR simple value</a> (major type 7, subtype 24) with a simple value of 21 (true) or 20 (false).
   </td>
  </tr>
  <tr>
   <td>
<a href="https://infra.spec.whatwg.org/#null">null</a>
   </td>
   <td>
A <a href="https://tools.ietf.org/html/rfc8949#section-3.3">CBOR simple value</a> (major type 7, subtype 24) with a simple value of 22 (null).
   </td>
  </tr>
</table>

Indefinite-length items are not allowed and _MUST_ be made a [CBOR definite length.](https://tools.ietf.org/html/rfc8949#section-3.2.2)

All CBOR tags _MUST_ be retained regardless of whether they are optional.

All four [Canonical CBOR rules](https://tools.ietf.org/html/rfc8949#section-4.2.1) listed in [[RFC8949](https://w3c.github.io/did-core/#bib-rfc8949)] _MUST_ be applied to all relevant data types.

All entries of a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) _MUST_ be included in the root [CBOR map](https://tools.ietf.org/html/rfc8949#section-3.1) (major type 5). 

When serializing a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) to its CBOR [representation](https://w3c.github.io/did-core/#dfn-representations), a [conforming producer](https://w3c.github.io/did-core/#dfn-conforming-producer) _MUST_ specify a media type of `application/did+cbor` to downstream applications such as described in [§ 7.1.2 DID Resolution Metadata](https://w3c.github.io/did-core/#did-resolution-metadata).

[6.4.2 CBOR Consumption \
](https://w3c.github.io/did-core/#consumption-1)All data structures expressed by a CBOR [representation](https://w3c.github.io/did-core/#dfn-representations) _MUST_ be deserialized into the [data model](https://w3c.github.io/did-core/#data-model) according to the following [consumption](https://w3c.github.io/did-core/#dfn-consumption) rules:

<table>
  <tr>
   <td><strong>CBOR Representation Type</strong>
   </td>
   <td><strong>Data Type</strong>
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR map</a> (major type 5)
   </td>
   <td>An <a href="https://infra.spec.whatwg.org/#maps">map</a>, where each data item of the CBOR map is added as an entry to the map with the entry key being the data item name and the value converted based on the CBOR type and, if available, entry definition, as defined here; as no order can be enforced for general CBOR maps, no insertion order is guaranteed.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> (major type 4), where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value is a <a href="https://infra.spec.whatwg.org/#list">list</a> or unknown
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#list">list</a>, where each value of the <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> is added to the list in order, converted based on the CBOR type of the array value, as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> (major type 4), where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value is an <a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>
   </td>
   <td>An <a href="https://infra.spec.whatwg.org/#ordered-set">ordered set</a>, where each value of the <a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR array</a> is added to the ordered set in order, converted based on the CBOR type of the array value as defined in this table.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3) where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value is a <a href="https://w3c.github.io/did-core/#dfn-datetime">datetime</a>
   </td>
   <td>A <a href="https://w3c.github.io/did-core/#dfn-datetime">datetime</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR string</a> (major type 3), where the <a href="https://w3c.github.io/did-core/#data-model">data model</a> entry value type is <a href="https://infra.spec.whatwg.org/#string">string</a> or unknown
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#string">string</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR integer</a> (major type 0 or 1), choosing the shortest byte representation
   </td>
   <td>An <a href="https://w3c.github.io/did-core/#dfn-integer">integer</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.1">CBOR floating-point number</a> (major type 7)
   </td>
   <td>A <a href="https://w3c.github.io/did-core/#dfn-double">double</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.3">CBOR simple value</a> (major type 7, subtype 24) with a simple value of 21 (True) or 20 (False)
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#boolean">boolean</a>.
   </td>
  </tr>
  <tr>
   <td><a href="https://tools.ietf.org/html/rfc8949#section-3.3">CBOR simple value</a> (major type 7, subtype 24) with a simple value of 22 (Null)
   </td>
   <td>A <a href="https://infra.spec.whatwg.org/#null">null</a> value.
   </td>
  </tr>
</table>

[CBOR indefinite-length items](https://tools.ietf.org/html/rfc8949#section-3.2.2) are not allowed and _MUST_ produce an error.

A duplicate key in the same CBOR map _MUST_ produce an error.

All CBOR tags _MUST_ be retained for CBOR [production](https://w3c.github.io/did-core/#dfn-production) regardless of whether they are optional.

If media type information is available to a [conforming consumer](https://w3c.github.io/did-core/#dfn-conforming-consumer) and the media type value is `application/did+cbor`, then the data structure being consumed is a [DID document](https://w3c.github.io/did-core/#dfn-did-documents), and the root element _MUST_ be a [CBOR map](https://tools.ietf.org/html/rfc8949#section-3.1) (major type 5) where all members of the object are entries of the [DID document](https://w3c.github.io/did-core/#dfn-did-documents). 

A [conforming consumer](https://w3c.github.io/did-core/#dfn-conforming-consumer) for a CBOR [representation](https://w3c.github.io/did-core/#dfn-representations) that is consuming a [DID document](https://w3c.github.io/did-core/#dfn-did-documents) with a root element that is not a [CBOR map](https://tools.ietf.org/html/rfc8949#section-3.1) (major type 5) _MUST_ report an error.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-8) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.8. Need tests for CBOR/JSON Production and Consumption 

_See github issue [did-test-suite#28](https://github.com/w3c/did-test-suite/issues/28), [did-test-suite#26](https://github.com/w3c/did-test-suite/issues/26)._




**Markus Sabadello:** those are about sections that don't have tests  
… 28 is about cbor  
… 26 is about json  
… there are test for jsonld production and consumption  
… and for generic sections about production and consumption that are not representation specific  
… it looks like there are no tests yet for cbor and json production and consumption  
… the cbor one is assigned to Orie and json is assigned to Daniel  

**Daniel Burnett:** we were hoping for someone like Jonathan to contribute on the cbor  

**Jonathan Holt:** doing my best to get back in the swing with DID contributions  

**Daniel Burnett:** daniel can you contribute on the json? the json format in particular was one of the biggest requests from Microsoft on day one of the working group  
… so we really want to make sure it's complete  

**Daniel Buchner:** the way we've gone about it I don't know... it's worked perfectly fine working jsonld as json and saying you don't have to resolve contexts  
… I can work on any tests that take that approach  
… that's what we're doing in our implementation  
… make sense?  
… are there bugs or issues out there that want it to be different than that?  

**Markus Sabadello:** i know some people want to treat jsonld and json as equivalent and to include `@context` in both and this has to do with long discussions we had  
… my personal opinion is this is not what the did core spec describes right now  
… it does not envision that json and jsonld are byte to byte equivalent  
… if that's what WG members want to do we should change the did core spec  
… right now on the test suite we need to take the normative statements  
… the open issues on the test suite they list the normative statements that need to be tested  
… so we need to work based on that  

**Justin Richer:** +1 to what markus was saying  
… one of the things that got brought up a necessary test condition is that a did doc that is described to be in plain json should be allowed to have the `@context` field and have it be a completely invalid value, and that should pass  
… that should get parsed, the `@context` dumped into the bucket  
… with whatever value it is  
… no checking if it's an array or string or anything  

> *Daniel Buchner:* Yes Justin, yeeeessss

> *Daniel Buchner:* Love everything you are saying right now

**Justin Richer:** so if you have the `@context` value with boolean false an d a plain json encoding by the way the did core spec is defined today that is allowable  
… because the re-serialization on the producer side needs to be able to place the appropriate context value and not just pass through blindly whatever it was handed  
… I will say I'm not personally familiar with the structure and function of the test suite code to suggest how to contribute this piece and don't have the bandwidth, I apologise for that  
… but that is the type of corner case we need to have tests cases for  
… if you're doing lazy validation that's not proving you're compliant  

**Daniel Buchner:** the interesting thing.. it doesn't say anything about must exclude properties... isn't lazy validation accurate?  
… if you had context with a bool and the spec doesn't say it has to be right isn't the way i'd write the test to not deal with that property?  
… lazy validation is the valid way to do it?  

**Justin Richer:** you need to go one step further because the spec says what to say with unknown properties  
… in this case `@context` would be an unknown property  
… you need to make sure things will accept things with an invalid `@context`  
… that's important  
… not enough to just say if i give you something an call it plain json but it's really jsonld that you'll be happy with that, that's not enough  
… we need to test these kinds of things  
… if you do that by ignoring it using a precise definition of ignore that's in the spec, that's fine  
… that's not lazy validation  
… that's explicitly handling unknown properties in a particular way  

**Daniel Buchner:** instead of completely avoiding it or not putting any lines of code that deal with unknown properties, it'll iterate all the properties and have some sort of if that says if you're not in the set.. log it.. do something.. recognise it exists.. if it is in the set do what you're supposed to do?  

**Justin Richer:** to be specific what it does is processes the serliazed property based on the type value of the serialized property and puts it into the properties map  
… there will be an `@context` with boolean value of false inside the ADM  

> *Daniel Buchner:* ok, this makes sense

> *Daniel Buchner:* thank you justin

**Justin Richer:** when it comes time to do a production from that ADM if you want to do it into jsonld your jsonld producer needs to be able to make sense of that bad `@context` value  
… and either throw an error there or replace it with a good `@context` value on thew ay out which is more likely  
… there are specific rules of how to handle these  
… from a code standpoint it does look like the else at the end of your validators  

**Daniel Buchner:** that's a good answer, thank you  

**Daniel Burnett:** issue 26 about json... Orie had asked in feb whether you might be able to contribute in writing some tests  
… largely this is in here because Microsoft fought hard for it  
… we want to make sure everyone else is not doing all of the test work  

**Daniel Buchner:** I'll try to do something about it  

**Daniel Burnett:** I think that's it for the test issues  

</details>

**Comment by OR13** [comment]
I am removing myself from this issue.

I think testing CBOR is a mistake and waste fo time, I have not seen evidence of any real implementation for `did+cbor`... I would prefer we drop the representation from the spec, and the tests, and that we tackle `did+dag+cbor` and `did+ld+cbor` which seem to be the actual thing people care about.

**Comment by msporny** [comment]
@OR13 has not seen evidence of any real implementation for did+cbor and has withdrawn his offer to implement these tests. I agree with @OR13 that we should drop the CBOR section due to no real implementations surfacing.

If anyone would like to see the CBOR section preserved in the specification, you will have to write all the tests for it and find at least two independent implementers. 

/cc @jonnycrunch

**Comment by jonnycrunch** [comment]
Dude, seriously!? As I discussed on Thursday I just starting working on this.  Seems very straightforward to give a Hex representation and parse with the nodejs cbor library.

**Comment by msporny** [comment]
> Dude, seriously!? 

Yes. :)

I'm not happy about it either, given the amount of time I spent working on the CBOR section to align it with the rest of the specification. I was always concerned that this was going to happen (and feel like I was fairly vocal about it... being dragged into it, kicking and screaming all the way). 

I do believe did+cbor is still implementable... it's just that no one has stepped forward and said their DID Method is going to support the representation since we entered Candidate Recommendation.

> As I discussed on Thursday I just starting working on this. Seems very straightforward to give a Hex representation and parse with the nodejs cbor library.

That's not the hard part. The hard part is writing all of the tests and then getting two independent implementations to step forward and submit their DID representations as did+cbor.

I know you'd do one for did+dag+cbor... and Digital Bazaar would do one for did+ld+cbor... but "did+cbor"? Haven't seen anyone step forward and say "Yeah, our DID Method is going to serialize as did+cbor!" <--- that's the hard part.

**Comment by OR13** [comment]
@jonnycrunch I see commenting on CBOR in DID Core as more of a risk to viable CBOR, then not commenting on it.... 

We should not pretend that CBOR got the same level of review, debate or even comprehension as JSON did during the WG... we rarely ever discussed it, when we did it was limited to a very small set of folks.

We are not prevented from writing a really excellent DID Document representation or `did+dag+cbor` and `did+ld+cbor` and using it... In a lot of ways the current `did+cbor` representation is misleading in that it appears to have more support, when it actually has less.

I'm not saying we shouldn't keep working on , I'm saying there is really good evidence that it hasn't met my bar for quality / review / support... my bar isn't the WG bar, but I think its a mistake to include a poorly understood / supported representation in the spec... its like serving a 3 course meal where one or the dishes isn't cooked all the way... throws the whole thing off when you get to the raw part.

**Comment by msporny** [comment]
Reminder that complete tests, including review, auditing, and at least one implementation, are due for this item by the end of this month.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-05-04-did#section3) on 2021-05-04

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-05-04-did#resolution1):  remove CBOR from the DID Core Specification, publish it as a WG Note, and add CBOR to the DID Spec Registries with a reference to the WG Note***

<details><summary><i>View the transcript</i></summary>

### 3. CBOR section 

_See github issue [did-test-suite#28](https://github.com/w3c/did-test-suite/issues/28)._




**Brent Zundel:** Chair things.  
… On the 13th of April, the chairs set a deadline for tests to be written.  
… for the end of April - and stated at that time that any normative statements that were untestable because no tests were written, would have to be removed from the specification.  
… What this means for group is need to decide what to do with the CBOR section.  
… Issue where CBOR production/consumption rules discussed [at a meeting in April](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-13-did#section4)  
… It is clear from those comments that the concerned parties were aware of the need for tests to be written. There was also a [special topic call on the 8th of April](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-08-did-topic)  
… that focused primarily on the CBOR section and how to test it, with concerned parties.  
… I outline all of this to make very clear that communication has been clear, and that all efforts have been made, as chairs and editorial staff, to encourage the writing of these tests.  
… With all of that said, we have some options, and will write these up as formal proposals once we get feedback from group.  
… Option 1: remove CBOR from DID Specification, and publish it as separate note.  
… Option 2: Remove CBOR from Specification to informative appendix of specification.  
… Option 3: remove it and don't do anything  
… My encouragement is to strongly consider option 1.  
… Opening to group for comments/suggestions.  

> *Amy Guy:* +1 option 1 .. makes sense as a note, which can be linked to from the registries, as any representation spec would be

**Justin Richer:** My concern for CBOR section as forcing function ... interoperability ... make JSON-based spec...  
… Of options, I think 1 is best (don't know if we are debating that) but concerned that publication as note would give less weight to the specification, and allow it to be functionally ignored by other components, for example the registries, which could morph in such a way to shut out CBOR or other representations.  

**Brent Zundel:** For record, I agree with you for my motivations for a CBOR section  
… Another option: to remove CBOR from spec, and change registries so that it can be registered as a new format in the registries.  

**Manu Sporny:** I agree with Justin's sentiment; I think it becomes fairly difficult to argue... we had an ADM so we could do things like CBOR  
… But where we are is not tests...  

> *Drummond Reed:* We have always said that new representations should be able to be registered in the DID Spec Registries.

**Manu Sporny:** I don't think anyone is actually implementing CBOR, they are doing variations on it. Digital Bazaar had: we are interested in CBOR-LD; would be interested in publishing as note.  
… danger of publishing CBOR as it is, it's a bit of an examplar - no one deploying it. would end up publishing note that no one intends to implement.  
… Biggest problem is it's in spec, but no tests, not implemented. I would be supportive of publishing as note, noting no one has implemented tests or implemented it.  
… Noting ... different implementation like CBOR-LD would be better, but not volunteering.  
… Having example of alternative in registry is a good idea.  

**Ivan Herman:** Just an additional point to what was said before: it may be still too early to talk about the details, but at some point in time in the coming months, we have to begin discussing how we imagine the world post this WG. What kind of continuation, etc.  
… It would be possible to say that in maintenance WG following this one, we put CBOR (or CBOR-LD, etc) as potential agenda item.  
… so to try to message community beyond the note, that we haven't given up.  
… We have to do what we have to do now, but long-term this group still intends to have CBOR coming at some point, when it's ready.  

**Brent Zundel:** Comments, suggestions?  
… Please suggest alternate proposals if needed to +1. More detail needed?  
… Add Ivan's suggestion that it should be input to WG?  

**Drummond Reed:** I'd love it for someone to speak to option 2, the appendix, the +/- of that.  
… My understanding is we are going to have/allow/provide for did-spec-registries to registry new representations, like for other things.  
… It could be a path for that. What is the relationship of publishing as note or in appendix, or as requirement for registry?  

**Ivan Herman:** Slight reservation about having as note because of time: do we have someone who will volunteer to write that note?  

**Justin Richer:** My concern with moving out into note or other thing is that it could allow for greater wiggle room in the registry  
… since this group has insisted on making its own registries - than is potentially helpful  
… because then we are functionally creating an abstraction from a single data representation type  
… - yes there are differences between JSON and JSON-LD but these are bigger than JSON and CBOR (?)  
… Concern about ... constructs. Any CBOR representation would be prohibited from translating a object key(?) to an abstract property name  
… We need to maintain flexibility... Concerned that without the weight of CBOR as first-class citizen, the registry could easily slip away from enabling that.  

> *Dmitri Zagidulin:* wait, but like.. the whole issue with the CBOR section is that nobody's put forth the implementations, test suite, etc. So regardless of if we're worried about its effect on the Registries, etc.. not much we can do here

**Manu Sporny:** I'll volunteer to move the spec test. It was written to be easy to move into a note.  
… I note that in the registries we have a section for representations that is empty right now.  
… Having the CBOR note would allow us to point to that.  
… To Justin's concerns: none of the spec test will change in any dramatic fashion. All the work done to ensure things like translate to binary and round-trip - text remains.  
… Exists in other sections that will be kept.  
… Some concerns others might not understand.  
… For example, CBOR-LD encoding depends on that language remaining.  
… DB uses it.  
… I would expect at least one editor to object to that language changing, so that it would enable CBOR-LD to exist  
… which has stronger needs than vanilla CBOR stuff.  

> *Justin Richer:* FWIW I'm not concerned with core spec language changing, but with registry language itself, which is managed separately.

**Manu Sporny:** The CBOR-LD translation is a binary transformation from the ADM and back into the ADM.  
… I'm not concerned we will lose that, but there is a risk - not sure what to do  
… I don't think the registries will be affected.  

> **Proposed resolution: remove CBOR from the DID Core Specification, publish it as a WG Note, and add CBOR to the DID Spec Registries with a reference to the WG Note** *(Brent Zundel)*

> *Manu Sporny:* +1

> *Amy Guy:* +1

> *Ivan Herman:* +1

> *Drummond Reed:* +1

> *Dmitri Zagidulin:* +1

> *Ted Thibodeau Jr.:* +1

> *Shigeya Suzuki:* +1

> *Brent Zundel:* +1

> *Adrian Gropper:* +1

> *Daniel Burnett:* +1

> *Charles Lehner:* +1

> *Geun-Hyung:* +1

> ***Resolution #1: remove CBOR from the DID Core Specification, publish it as a WG Note, and add CBOR to the DID Spec Registries with a reference to the WG Note***

**Brent Zundel:** with sadness, resolved.  

</details>

**Comment by msporny** [comment]
The CBOR section has been removed from the specification. Closing.
