### ISSUE TITLE
Need tests for Metadata Structure

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#31]
[7.3 Metadata Structure \
](https://w3c.github.io/did-core/#metadata-structure)

The structure used to communicate this metadata _MUST_ be a [map](https://infra.spec.whatwg.org/#maps) of properties. 

Each property name _MUST_ be a [string](https://infra.spec.whatwg.org/#string). 

Each property value _MUST_ be a [string](https://infra.spec.whatwg.org/#string), [map](https://infra.spec.whatwg.org/#maps), [list](https://infra.spec.whatwg.org/#list), [ordered set](https://infra.spec.whatwg.org/#ordered-set), [boolean](https://infra.spec.whatwg.org/#boolean), or [null](https://infra.spec.whatwg.org/#null). 

The values within any complex data structures such as maps and lists _MUST_ be one of these data types as well. 

All metadata property definitions registered in the DID Specification Registries [[DID-SPEC-REGISTRIES]](https://infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes) _MUST_ define the value type, including any additional formats or restrictions to that value (for example, a string formatted as a date or as a decimal integer).

The entire metadata structure _MUST_ be serializable according to the [JSON serialization rules](https://infra.spec.whatwg.org/#serialize-an-infra-value-to-json-bytes) in the [[INFRA]](https://www.w3.org/TR/2021/CR-did-core-20210318/#bib-infra) specification.

**Comment by peacekeeper** [comment]
@msporny I edited your comment to reflect the latest version of the spec.

**Comment by shigeya** [comment]
I'm wondering how we can test this statement:

> All metadata property definitions registered in the DID Specification Registries [DID-SPEC-REGISTRIES] MUST define the value type, including any additional formats or restrictions to that value (for example, a string formatted as a date or as a decimal integer).

How do we know property definitions on the test suite side? We just assume non-core properties to be in the spec registry?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-30-did#section7-4) on 2021-03-30

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.4. Need tests for Metadata Structure 

_See github issue [did-test-suite#31](https://github.com/w3c/did-test-suite/issues/31)._




**Shigeya Suzuki:** I almost finished writing tests besides one issue, related to the DID registry, as I commented in the issue.  
… Please look at the last comment I made.  
… The spec says all metadata property definitions registered in the registry must define a variable type.  
… I need a way to find this. Option 1: refer to did-spec-registries  
… Or we can assume that properties other than the core properties are registered.  
… I need some way to determine the list of types for this test.  

**Brent Zundel:** Thank you for the overview  

> *Charles Lehner:* Thank you all for your work.

**Brent Zundel:** Special Topic call this Thursday  

---

</details>

**Comment by shigeya** [comment]
@msporny We don't want to close this yet.. The test (potentially) referring to DID SPEC REGISTRY is not yet complete..

**Comment by msporny** [comment]
> @msporny We don't want to close this yet.. The test (potentially) referring to DID SPEC REGISTRY is not yet complete..

Ok, reopened.

**Comment by shigeya** [comment]
Let me quote the statement again here:
> All metadata property definitions registered in the DID Specification Registries [DID-SPEC-REGISTRIES] MUST define the value type, including any additional formats or restrictions to that value (for example, a string formatted as a date or as a decimal integer).

From the core spec point of view, the above statement is not testable within the core tests. This spec text needs to be placed in DID-SPEC-REGISTRIES, not within core spec. I honestly have no idea whether we can treat this statement as "human testable."

From a different perspective: since the current test implementation runs the whole test against the transcript of interaction with multiple method implementations, it is desirable to test properties defined in DID-SPEC-REGISTRIES. In this case, we need a machine-readable -- at least partial -- DID-SPEC-REGISTRY.

I think there are three options:

1. Eliminating the above statement
2. Rewrite the above statement to move the test to DID-SPEC-REGISTRIES
3. Rewrite the above statement to remove (direct) dependency on DID-SPEC-REGISTRIES.

It is possible to create an optional configuration parameter that may hold machine-readable (possibly partial) DID-SPEC-REGISTRIES, which can be usable for the above option 3.

(Note: due to schedule conflict, I can't attend the special topic call this week)

**Comment by msporny** [comment]
> From the core spec point of view, the above statement is not testable within the core spec.

Correct.

> This spec text needs to be placed in DID-SPEC-REGISTRIES, not within core spec. 

Yes, agreed.

> I honestly have no idea whether we can treat this statement as "human testable."

It is human testable. A human can check to see if "All metadata property definitions registered in the DID Specification Registries [DID-SPEC-REGISTRIES] define the value type, including any additional formats or restrictions to that value (for example, a string formatted as a date or as a decimal integer)."

I suggest we do the second option (if we don't have to go through another CR to do it), or just flag the statement as human testable and not something the WG intended to test. We have lots of these sorts of statements in the DID Methods section.

**Comment by msporny** [comment]
I believe we can raise a new issue just for the one test that @shigeya found that was human testable, and then close this issue.

Raised the issue here: https://github.com/w3c/did-test-suite/issues/65

Closing.

**Comment by shigeya** [comment]
Yes, I should have close this and open a new one early. thanks.
