### ISSUE TITLE
need clear instructions for implementers

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-test-suite#33]
Implementers need a clear set of instructions that includes:
1. a pointer to the tests themselves and general information about what is tested
2. guidance on how to test and submit an implementation report
3. How to view the summary of submitted reports

I think number three is probably covered, but I'm not finding the first two.

**Comment by brentzundel** [comment]
https://github.com/w3c/vc-test-suite may serve as an example

**Comment by OR13** [comment]
This is blocked by enough "good examples" of "real did methods"

**Comment by OR13** [comment]
I will add instruction when suite stabilizes and covers reasonable amount of the spec.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-30-did#section7-2) on 2021-03-30

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.2. need clear instructions for implementers 

_See github issue [did-test-suite#33](https://github.com/w3c/did-test-suite/issues/33)._




**Brent Zundel:** When an implementer goes to the test suite, there needs to be a clear set of instructions for submitting tests.  
… Last time I looked, I didn't see ... guidance on submitting an implementation report.  

> *Kyle Den Hartog:* +1 definitely ran the tests saw they passed and went "Huh, I didn't connect any of my code though"

**Markus Sabadello:** I agree with what Manu said earlier. Test suite needs to be restructured. Not entirely clear what an implementor would submit.  
… There are a number of PRs using different formats ... needs to be reconciliated a bit.  

**Brent Zundel:** Will someone take this issue  

**Orie Steele:** I will ... assuming ...  

**Brent Zundel:** I have no problem with that  

</details>

**Comment by msporny** [comment]
> This is blocked by test suite refactoring and enough "good examples" of "real did methods"

This should be unblocked with the merge of PR #52.

The general instructions for implementers are:

* Look at packages/did-core-test-server/suites/implementations/
* Copy an example for a did, resolver, dereferencer, etc. that looks similar to what you want to do.
* Add that file to the respective test suite. For example, for DID Method Documents, add it to did-core-properties/default.js

... and that's pretty much it.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-7) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.7. need clear instructions for implementers 

_See github issue [did-test-suite#33](https://github.com/w3c/did-test-suite/issues/33), [did-test-suite#32](https://github.com/w3c/did-test-suite/issues/32)._




**Markus Sabadello:** also related to refactoring  
… implementers of a did method or the spec in another way so they know how exactly they submit their data  

**Daniel Burnett:** pretty straightforward  

**Markus Sabadello:** last two are about sections of the spec which are still missing  
… there are not tests yet  

</details>

**Comment by msporny** [comment]
Instructions on how to submit implementations are now here:

https://github.com/w3c/did-test-suite#adding-your-did-implementation

Closing.
