### ISSUE TITLE
Use of better jest matchers

### ISSUE THREAD

**Issue by shigeya** [w3c/did-test-suite#36]
By using matchers provided by packages like [`jest-extend`](jest-community/jest-extended), we can simplify, like this

>    expect(utils.isAsciiString(method)).toBe(true);

to:

>    expect(method).toBeString();

There are a set of jest matchers available for primitives like arrays and maps. 

Also, we can implement customized jest matchers (like the one matches with DID or DID URL string pattern) which will greatly simplify the tests with better readability.

Note: Adding the library make the whole test slightly slower (1.5sec to 1.8sec in my environment), but it will be negligible once the whole set of tests are available.

If this way of the use of matchers is acceptable, I can write a PR for that.

**Comment by shigeya** [comment]
I now realize the above example is wrong (it's ASCII only). But the point is to use the jest matchers as much as possible.

**Comment by OR13** [comment]
I would propose writing a helper function and using it for these common cases, like "valid URL or valid ASCII"

**Comment by shigeya** [comment]
I think we want to have mathers for most of the cases which call funcitons in the `utils` module.

For the most of the core types, we can use jest-extended.  I propose to write a notes on preferred way to write test using matchers.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-30-did#section7-1) on 2021-03-30

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.1. Use of better jest matchers 

_See github issue [did-test-suite#36](https://github.com/w3c/did-test-suite/issues/36)._




**Brent Zundel:** shigeya, can you talk about it?  

**Shigeya Suzuki:** There are several ways to write tests, mentioned in this ... whether the specific string in a variable is actually a string or not, and so on.  
… After filing this issue, I found that there are variations of the test against, for example, if a variable is a string or not, there is variation on how to write the test.  
… I think it is better to use the same pattern in the test. Not necessarily as matchers as I stated here, but at least should use the same pattern for the entire test.  
… If we use matchers, we can simplify both the expressions and the test.  
… So I think it is better to use matchers.  

> *Charles Lehner:* +1

**Manu Sporny:** I agree with shigeya.  
… There is a certain amount of cleanup ... I agree we should use the matchers shigeya is mentioning. +1  

**Brent Zundel:** Is anyone willing to be assigned to this issue?  

**Shigeya Suzuki:** I can work on it.  

**Brent Zundel:** Thank you  

> *Charles Lehner:* Next issue raised by me...

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-6) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.6. Use of better jest matchers 

_See github issue [did-test-suite#36](https://github.com/w3c/did-test-suite/issues/36)._




**Markus Sabadello:** next is about using jest matchers  
… I'm not a javascript expert so I probably can't explain that well  
… shigeya is here, maybe..?  

**Shigeya Suzuki:** a way to define matches which is construct like a ?? sometimes useful whether you want to test whether the expected variable is in a string  
… or certain kind of string  
… eg. we have tons of the did identifier syntax  
… so we are going to have a string that matches.. can be easier to do it.. easy to change the syntax if we want to change it  
… I'm going to write matchers  
… maybe later this week or early next week  
… so we can refactor the entire test suite to be simpler  
… that's the idea  

**Markus Sabadello:** sounds fantastic  
… has exactly to do with this kind of parallel implementation and code duplication we have right now  
… at least three different people who have worked on tests for different sections have all writen some kind of test code that checks if a string is a valid did that conforms with the syntax because that's something that occurs in many parts of the spec  
… therefore different people have implemented a test for did syntax in different ways  
… if we had a jest matcher for the test suite that does that it will save everybody work  
… and result in a more correct test suite  
… next two are self explanatory  

</details>

**Comment by shigeya** [comment]
I think we can close this.
