### ISSUE TITLE
Producer tests should be of the ADM not resolution result

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#48]
We need the producer tests to be of an ADM representation, and not a resolution result

**Comment by OR13** [comment]
See concerns here: https://github.com/w3c/did-test-suite/pull/41#issuecomment-812023105

**Comment by OR13** [comment]
@clehner I will try to assign you per our conversation on the call

**Comment by clehner** [comment]
[Section 4. Data Model](https://www.w3.org/TR/did-core/#data-model) implies that the DID document data model contains representation-specific entries:
> The DID document data model contains at least two different classes of entries. The first class of entries is called properties, and is specified in section § 5. Core Properties. The second class is made up of representation-specific entries, and is specified in section § 6. Representations.

But [Section 6. Representations](https://www.w3.org/TR/did-core/#representations) implies that the DID document data model is seperate from the representation-specific entries:
-  "A conforming producer MUST take a DID document data model and a representation-specific entries map as input into the production process" (#24)
- "... representation-specific entries map which is returned after the consumption process completes ... and return the DID document data model" (#25)

#45 splits the input for consumption into the DID document data model and representation-specific entries map, as that is how I interpreted Section 6 - while #41 takes the representation-specific entries out of the same object input as the DID document data model, which is consistent with Section 4.

Having the representation-specific entries in the same object as the DID document data model allows for using the object also as a JSON-LD representation, as in a resolution result. This could be useful for unifying parts of the test suite, i.e. the conformingConsumer test cases added in #45 could be incorporated into the main test config like the producer test cases were in #41. Should we do that, to simplify things?

Alternatively, we could distinguish between the representation-specific entries and the core properties within the DID document data model, changing consumption input / production output to something like this:
```
"didDocumentDataModel": {
  "representationSpecificEntries:: {
    "context": [
      "https://www.w3.org/ns/did/v1"
    ]
  },
  "coreProperties": {
    "id": "did:example:1234"
  }
}
```
Would that be worth the added verboseness, and incompatibilty with the resolution result format, for the purpose of corresponding more closely to the specification?

**Comment by msporny** [comment]
I have raised PR #52 to restructure the test suite to make implementing the above easier. I will do that after PR #52 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-5) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.5. Producer tests should be of the ADM not resolution result 

_See github issue [did-test-suite#48](https://github.com/w3c/did-test-suite/issues/48)._




**Markus Sabadello:** next is substantive  
… other issues related  
… how to properly test the ADM and different representations  
… a topic that has taken time on the working calls to specify that in did core  
… now we're working on how to properly test that in the test suite  
… there are existing tests that have been merged related to production and consumption and this issue is to keep track of improvements that may have to be made onto those tests  
… to distinguish between the did doc as a data model and the did doc as a concrete representation  
… ideally the test suite would distinguish between the ADM and the representations in clean way  
… production tests and consumption tests and resolution tests would either operation on the data model or the representations depending on what the spec says  

**Daniel Burnett:** manu's last comment was that you, orie and cel need to get to gather to decide on a plan  
… do you have a plan?  

**Markus Sabadello:** I don't think we have that yet  
… special topic call might be an opportunity  
… a case where things have moved very fast in past weeks, people have worked in parallel and done certain things slightly differently  
… I think cel has done it really nicely  
… very clean distinction between those layers  

**Jonathan Holt:** one thing i was working on before was representing the ADM in ABNF rules  
… that is supported in the CDDL  
… I haven't seen the test suite in a while, getting back up to speed  
… but curious if I were to write an ABNF rule for the entire spec would that be received well?  
… would it be a solution? I have a hard time with the ADM being too abstract, I can't test for it  
… I haven't followed the typescript representation orie has been working on  

**Markus Sabadello:** i suspect people would ask how an ABNF applies to an abstract data model  
… probably a deeper conversation  
… ABNF is a way of specifying a syntax  
… specify an ABNF for one of the representations, not sure how you'd use it to describe the ADM  
… but maybe I'm missing something  

**Daniel Burnett:** probably a good topic for Thursday  
… we're missing some people today  
… would be good to raise on Thursday or to submit as an issue  

**Markus Sabadello:** point of the test suite is to test all the normative statements in the did core spec  
… we need to prove that it is possible to implement all those statements  
… if that can be done with an ABNF maybe that would be useful but we should look at how exactly that would be done and which statements in the spec that would test  

</details>

**Comment by msporny** [comment]
PR #52 was merged, which powers the tests off of the ADM instead of the representation. This is done. Closing.
