### ISSUE TITLE
Proposal to refactor the input json into js files

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#49]
so we can build larger configurations from smaller more atomic ones.

**Comment by OR13** [comment]
@peacekeeper and I discussed that this was probably better to tackle at the same time as the other refactoring you signed up for :)

**Comment by msporny** [comment]
PR #52 has been raised to do this, and I believe achieves this part of the refactoring. We could refactor more, but I want to make sure everyone is on board with the current direction in #52 before going further.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-4) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.4. Proposal to refactor the input json into js files 

_See github issue [did-test-suite#49](https://github.com/w3c/did-test-suite/issues/49)._




**Markus Sabadello:** next is similar, about restructuring the input files  
… in an early version there was a single gigantic input file with lots of dids and did docs  
… and production and consumption inputs and outputs for multiple dids and did methods  
… in a single file  
… this issue is about organising that better and splitting up that one file  
… which will be easier for people to submit their own data  
… uncontroversial  

</details>
