### ISSUE TITLE
Proposal to create a suite per major section of the spec

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#50]
This will reduce conflicts and improve codeownership, it will also enable better testing in isolation, which should make it easier to work on tests.

**Comment by OR13** [comment]
Similar reasoning for assigning you this as we had for https://github.com/w3c/did-test-suite/issues/49... make sure to delegate if its not achievable.

**Comment by peacekeeper** [comment]
+1 to creating a separate suite for each major section.

**Comment by msporny** [comment]
I have raised PR #52 to do this. Please review and see if the refactoring works for everyone. It's not entirely split on section... some of the stuff was dicey, like the metadata structure... but the rest is split on section.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-3) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.3. Proposal to create a suite per major section of the spec 

_See github issue [did-test-suite#50](https://github.com/w3c/did-test-suite/issues/50)._




**Markus Sabadello:** relatively simple  
… internal restructuring to organise the test suite into multiple suites which each contain tests related to one section  
… in the initial draft of the test suite we had one suite which contained a huge list of tests  
… this is a way of dividing and structuring the test suite a bit better  
… will result in better reports  

**Daniel Burnett:** also editorial  

</details>
