### ISSUE TITLE
How will be produce visualization of the test results

### ISSUE THREAD

**Issue by OR13** [w3c/did-test-suite#51]
- At minimum we want to see Green checkmarks Red X's for tests in the spec.
- List fo implementers for every test.
- Goal is in each row to have at least 2 greens.
- Having a human readable description of what each test does it a nice to have.
- Also good to have a few words on each implementation

**Comment by OR13** [comment]
we should hold off on this until we feel the suite is very stable.

But we can gather snippets and examples here in the meantime

**Comment by OR13** [comment]
We should also make sure we take advantage of automated visualization, since this is free with JEST.

- https://transmute-industries.github.io/did-core/

**Comment by OR13** [comment]
Another example from the WG call:

- https://w3c.github.io/publ-tests/test_reports/manifest_processing/index.html

**Comment by msporny** [comment]
I have started to try to structure the test output in a more hierarchical, logical fashion in PR #52. The general structure is: major section of the spec > implementation being tested > minor section of the spec > specific variation of implementation being tested > specific normative statement. For example:

* 3.x Identifier
  * id:key (2018 cryptosuite) - did-method-key-js - Digital Bazaar
    * 3.1 DID Syntax
      * `did:key:zMk623kjsd...8fd`
        * 3.1 DID Syntax - MUST be a valid URL.


It's a bit awkward, but given that test suite implementers have chosen to test different sections of the spec in different ways, it's the only logical structuring that we can do, AFAICT.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-2) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.2. How will be produce visualization of the test results 

_See github issue [did-test-suite#51](https://github.com/w3c/did-test-suite/issues/51)._




**Markus Sabadello:** I'm not familiar with this one, self describing  
… test report in the form of a json file  
… a number o fways of how to render that in html  

**Daniel Burnett:** even though we don't have a notion of editorial with the test suite, this falls into that category  
… presentation, not about the actual running of the tests  
… in the end orie will decide something but if you have an opinion, express it  

**Ivan Herman:** we discussed this with orie on the last call  
… we will have to produce some sort of report of the whole CR phase, test results, implementations, etc  
… there are other examples in other WGs  
… I can help with that at the end  
… the only thing it affects right now is that there should be a clear structured way of characterising each test  
… metadata about the test  
… and about the implementations  
… once those are there in some format, whatever format, we can do something at the end  

</details>

**Comment by msporny** [comment]
This has been implemented by @shigeya, closing.
