### ISSUE TITLE
Missing tests in DID Resolution and DID URL Dereferencing

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-test-suite#53]
https://github.com/w3c/did-test-suite/pull/43 has been merged to address https://github.com/w3c/did-test-suite/issues/29 and https://github.com/w3c/did-test-suite/issues/30, but there are still a few TODOs in the DID Resolution and DID URL Dereferencing tests.

- [x] _All conformant DID resolvers MUST implement the DID resolution functions for at least one DID method and MUST be able to return a DID document in at least one conformant representation._
    - Test not implemented yet.

- [x]  _If the resolution is successful, and if the resolve function was called, this MUST be a DID document abstract data model (a map) as described in § 4. Data Model that is capable of being transformed into a conforming DID Document (representation), using the production rules specified by the representation._
    - Test if the DID document abstract data model is capable of being transformed into a conforming DID Document (representation). This should re-use code from other tests (production).

- [x]  _The caller of the resolveRepresentation function MUST use this value when determining how to parse and process the didDocumentStream returned by this function into the data model._
    - This should re-use code from other tests (consumption).

- [ ]  _A conforming DID Method specification MUST guarantee that each equivalentId value is logically equivalent to the id property value._
    - I don't think this is testable.

- [ ]  _equivalentId is a much stronger form of equivalence than alsoKnownAs because the equivalence MUST be guaranteed by the governing DID method._
    - I don't think this is testable.

- [ ] A conforming DID Method specification MUST guarantee that the canonicalId value is logically equivalent to the id property value.
    - I don't think this is testable.

- [x]  _To dereference a DID fragment, the complete DID URL including the DID fragment MUST be used._
    - Not sure yet how to test this.

- [x]  _If the contentStream is a DID document, this MUST be a didDocumentMetadata structure as described in DID Resolution._
    - This should re-use code from other tests (metadata structure).

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-06-did#section7-1) on 2021-04-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.1. Missing tests in DID Resolution and DID URL Dereferencing 

_See github issue [did-test-suite#53](https://github.com/w3c/did-test-suite/issues/53)._




**Markus Sabadello:** the first one I raised. I submitted tests for did resolution and url dereferencing sections, which have bene merged  
… this issue tracks sentences in those sections that are not yet covered  
… eg. in did core there's a statement that says a conforming did method spec must guarantee that each equivalent id value is logically equivalent to the id property value. Not sure if this is testable at all  
… that's what this issue is about  

**Daniel Buchner:** we had one we were taking about in a PR that we were going to mod some language..  
… did we decide if we're going to accept... the equivalent stuff the method defines.. there are ways inside methods to figure this out  
… can we accept a test where an implementation test takes in a did and says I've got an equivalent and id property, I'll save both - test success  
… is that acceptable?  

**Markus Sabadello:** I don't know, the did core spec says a conforming did method must guarantee that some identifiers are logically equivalent. I don't know how to write a tests that tests that the did method spec guarantees that  

**Daniel Buchner:** it would happen inside.. i don't know that the external thing would be testing that  
… eg. the did spec says the did method should determine the correct keys to put in the did doc.. I don't know how it's doing that, we can't test inside all the methods how they're doing that.. grabbing keys and sticking them in a json object.. but because we tell them they output the correct json doc we assume they get the correct keys  

**Daniel Burnett:** if you join on Thursday that would be a great time to discuss the topic  

**Daniel Buchner:** okay  

> *Daniel Buchner:* I am, will do

**Daniel Burnett:** and you were also signed up to write some tests? good chance to talk about that and the question  

**Markus Sabadello:** this is one case where I just didn't know how to write a test, maybe someone can help in a working session  

**Daniel Buchner:** I don't think there is a way  

**Markus Sabadello:** that might occur in several more times  
… we discover some statement where we don't have a way of testing it in an automated wya  
… not sure then what we need to do  
… we've had discussions a few times if you can still have normative statements in the spec without testing them in an automated way  
… in that case they'd have to be demonstrated in some other way that it is possible to implement them  
… we've had those discussions, manu and ivan know better how that works  
… if we can't demonstrate that it's possible to implement then the alternative is to not use normative language  
… and just say did methods are expected to guarantee that instead of saying MUST  
… other people know better what to do in these cases  

> *Daniel Buchner:* DID Key and some other initial state long-form type DIDs are really the only ones you could 'test' if they have included the correct keys

> *Daniel Buchner:* DID Key is a key, so obviously you can know what the right key should be

> *Daniel Buchner:* But any method that has had a rotation occur forms the correct key associations internally

> *Daniel Buchner:* so that's always going to be specific to the method

> *Daniel Buchner:* as everything in the DID Doc is

> *Daniel Buchner:* including Service Endpoints

</details>

**Comment by TallTed** [comment]
I suggest using github's checkbox feature for your action bullets.  They have proven helpful elsewhere, especially as/when time gets tighter.

**Comment by clehner** [comment]
>  * _To dereference a DID fragment, the complete DID URL including the DID fragment MUST be used._
>    
>    * Not sure yet how to test this.

Idea: a test could require that there are some two input DID URLs and corresponding dereferencing results, such that the input DID URLs differ only by the DID fragment, and the dereferencing results are different. This would show that the DID fragment was used in the dereferencing process since it results in a different output.

Or a simpler way would be just to check that some input DID URL has a DID fragment.

**Comment by peacekeeper** [comment]
Closing this in favor of https://github.com/w3c/did-test-suite/issues/76 where tested statements are also being tracked.
