### ISSUE TITLE
Should implementation files contain `representationSpecificEntries` alongside each representation?

### ISSUE THREAD

**Issue by msporny** [w3c/did-test-suite#64]
Should `representationSpecificEntries`  and `properties` be stored with each DID entry in implementation files, or should they be split -- with `properties` being at a higher level, and `representationSpecificEntries` going beside each representation.

@OR13 suggested that we should store `representationSpecificEntries` alongside `properties` here: https://github.com/w3c/did-test-suite/pull/55#discussion_r612827456

@peacekeeper suggested that they belong with each `representation` (which is what was decided on the 2021-04-13 telecon): https://github.com/w3c/did-test-suite/pull/55#discussion_r614238588

Tracking the disagreement here.

The outcome of the decision has no bearing on the output from the test suite.

**Comment by OR13** [comment]
I think the way that we structure tests biases folks towards thinking about how to implement the ADM.

Since we support multiple representations I think it's helpful to show the same did document in multiple representations and in its ADM form.

In order to avoid needless and potentially error prone duplication, I suggest the following structure:

1. ADM = (coreEntries + repEntries // names do not matter to me.
2. Rep 1 = (contentType, serialization)
3. Rep 2 = (contentType, serialization)

The serialization needs to hold everything from production and provide everything during consumption.

If you do this instead:

1. ADM = ( coreEntries )
2. Rep 1 = ( contentType, serialization, repEntries )
3. Rep 2 = ( contentType, serialization, repEntries )

You are making the tests confusing.

**Comment by peacekeeper** [comment]
As the name suggests, representation-specific entries are specific to a representation and therefore in the test structure should appear under the representation (e.g. `@context` under `application/did+ld+json`).

I don't see how putting "representation-specific entries" outside of a specific representation makes any sense....

**Comment by OR13** [comment]
@peacekeeper because production requires them to be outside... since you can't produce from a representation.

**Comment by OR13** [comment]
production is: coreEntries + repEntries  => representation

**Comment by msporny** [comment]
We have lots of implementations now, people don't seem to be concerned about the current structure, closing.
